#!/usr/bin/env python
# Even fabinacci numbers

"""
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

Answer = 4613732

yield is like as return: A generator is a special type of function that can be 
used as an iterator. A generator function is any function which uses the yield
statement.--> when you use 'yield' as a method return, it returns a python 
'generator' type.
"""

def even_fib(num):
    a, b = 0, 1
    while a < num:
        if not a % 2:
            yield a
        a, b = b, b + a

print sum(even_fib(4000000))
