"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

Max = 10000000

triangle = [n * (n+1) /2 for n in range(0, Max)]
pentagonal = [n* (3*n-1)/2 for n in range(0, Max)]
hexagonal = [n * (2*n -1) for n in range(0, Max)]

pentagon_dict = dict.fromkeys(pentagonal, 1)
hexagon_dict = dict.fromkeys(hexagonal, 1)
for x in range(286, Max):
    a =  triangle[x]
    if pentagon_dict.has_key(a) and hexagon_dict.has_key(a):
        print a
        break

